### ISSUE TITLE
Implement traits on the ciphers

### ISSUE THREAD

**Issue by arosspope** [arosspope/cipher-crypt#5]

**Comment by dex-r** [comment]
Looking at the current implementation of the traits, I was wondering whether the decrypt trait (and possibly encrypt) should return a Result<String> rather than just a String. Some of the ciphers listed in the readme will fail when trying to decrypt bad input e.g. The Baconian cipher will fail if the ciphertext length is not a multiple of 5. I guess an alternative would be to ignore parts of the ciphertext, but i think that's a bit presumptuous.

**Comment by arosspope** [comment]
I was thinking the same thing. Already there are some cases in some of the ciphers were certain cases should return an Err instead.

If you were so inclined could you create a seperate issue and implement result returns? 😊 If not, ill probably do it at some point

**Comment by arosspope** [comment]
See PR #7
